# Generated by Django 4.0 on 2022-03-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('UserProfile', '0002_userinfo_address_userinfo_category_userinfo_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='userprofil/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skill.skill'),
            preserve_default=False,
        ),
    ]
