# Generated by Django 4.0 on 2022-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('UserProfile', '0003_userinfo_profile_pic_userinfo_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='skill',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='skill',
            field=models.ManyToManyField(to='skill.Skill'),
        ),
    ]
