# Generated by Django 4.0 on 2022-03-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_userinfo_dgree_userinfo_hsccs_userinfo_sccs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='college_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='hschool_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sschool_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
